package com.transglobalexpress.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-25T20:46:25.144+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://services.transglobalexpress.co.uk/", name = "BookSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface BookSoap {

    @WebMethod(operationName = "IsAirWaybillAvailable", action = "http://services.transglobalexpress.co.uk/IsAirWaybillAvailable")
    @RequestWrapper(localName = "IsAirWaybillAvailable", targetNamespace = "http://services.transglobalexpress.co.uk/", className = "com.transglobalexpress.services.IsAirWaybillAvailable")
    @ResponseWrapper(localName = "IsAirWaybillAvailableResponse", targetNamespace = "http://services.transglobalexpress.co.uk/", className = "com.transglobalexpress.services.IsAirWaybillAvailableResponse")
    @WebResult(name = "IsAirWaybillAvailableResult", targetNamespace = "http://services.transglobalexpress.co.uk/")
    public com.transglobalexpress.services.AirWaybillAvailableResponse isAirWaybillAvailable(
        @WebParam(name = "apiKeyId", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String apiKeyId,
        @WebParam(name = "bookingReference", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String bookingReference
    );

    @WebMethod(operationName = "BookQuote", action = "http://services.transglobalexpress.co.uk/BookQuote")
    @RequestWrapper(localName = "BookQuote", targetNamespace = "http://services.transglobalexpress.co.uk/", className = "com.transglobalexpress.services.BookQuote")
    @ResponseWrapper(localName = "BookQuoteResponse", targetNamespace = "http://services.transglobalexpress.co.uk/", className = "com.transglobalexpress.services.BookQuoteResponse")
    @WebResult(name = "BookQuoteResult", targetNamespace = "http://services.transglobalexpress.co.uk/")
    public com.transglobalexpress.services.OrderResponse bookQuote(
        @WebParam(name = "apiKeyId", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String apiKeyId,
        @WebParam(name = "quoteId", targetNamespace = "http://services.transglobalexpress.co.uk/")
        int quoteId,
        @WebParam(name = "serviceId", targetNamespace = "http://services.transglobalexpress.co.uk/")
        int serviceId,
        @WebParam(name = "deliveryAddress", targetNamespace = "http://services.transglobalexpress.co.uk/")
        com.transglobalexpress.services.QuoteAddress deliveryAddress,
        @WebParam(name = "collectionAddress", targetNamespace = "http://services.transglobalexpress.co.uk/")
        com.transglobalexpress.services.QuoteAddress collectionAddress,
        @WebParam(name = "packingList", targetNamespace = "http://services.transglobalexpress.co.uk/")
        com.transglobalexpress.services.ArrayOfQuotePackingListItem packingList,
        @WebParam(name = "consignmentSummary", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String consignmentSummary,
        @WebParam(name = "consignmentValue", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.math.BigDecimal consignmentValue,
        @WebParam(name = "vatNumber", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String vatNumber,
        @WebParam(name = "eoriNumber", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String eoriNumber,
        @WebParam(name = "purchaseOrderNumber", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String purchaseOrderNumber,
        @WebParam(name = "skippingPackingList", targetNamespace = "http://services.transglobalexpress.co.uk/")
        boolean skippingPackingList,
        @WebParam(name = "collectionRequired", targetNamespace = "http://services.transglobalexpress.co.uk/")
        boolean collectionRequired,
        @WebParam(name = "collectionDate", targetNamespace = "http://services.transglobalexpress.co.uk/")
        javax.xml.datatype.XMLGregorianCalendar collectionDate,
        @WebParam(name = "requiredCover", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.math.BigDecimal requiredCover,
        @WebParam(name = "failOnCarrierError", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.Boolean failOnCarrierError
    );
}
