package com.transglobalexpress.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-25T20:47:14.292+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://services.transglobalexpress.co.uk/", name = "OrderSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderSoap {

    @WebMethod(operationName = "GetOrder", action = "http://services.transglobalexpress.co.uk/GetOrder")
    @RequestWrapper(localName = "GetOrder", targetNamespace = "http://services.transglobalexpress.co.uk/", className = "com.transglobalexpress.services.GetOrder")
    @ResponseWrapper(localName = "GetOrderResponse", targetNamespace = "http://services.transglobalexpress.co.uk/", className = "com.transglobalexpress.services.GetOrderResponse")
    @WebResult(name = "GetOrderResult", targetNamespace = "http://services.transglobalexpress.co.uk/")
    public com.transglobalexpress.services.OrderResponse getOrder(
        @WebParam(name = "apiKey", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String apiKey,
        @WebParam(name = "orderReference", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String orderReference
    );
}
