package com.transglobalexpress.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-25T20:47:14.322+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "Order", 
                  wsdlLocation = "http://staging.services.transglobalexpress.co.uk/Order.asmx?WSDL",
                  targetNamespace = "http://services.transglobalexpress.co.uk/") 
public class Order extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.transglobalexpress.co.uk/", "Order");
    public final static QName OrderSoap = new QName("http://services.transglobalexpress.co.uk/", "OrderSoap");
    public final static QName OrderSoap12 = new QName("http://services.transglobalexpress.co.uk/", "OrderSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://staging.services.transglobalexpress.co.uk/Order.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Order.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://staging.services.transglobalexpress.co.uk/Order.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public Order(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Order(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Order() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Order(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Order(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Order(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OrderSoap
     */
    @WebEndpoint(name = "OrderSoap")
    public OrderSoap getOrderSoap() {
        return super.getPort(OrderSoap, OrderSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderSoap
     */
    @WebEndpoint(name = "OrderSoap")
    public OrderSoap getOrderSoap(WebServiceFeature... features) {
        return super.getPort(OrderSoap, OrderSoap.class, features);
    }


    /**
     *
     * @return
     *     returns OrderSoap
     */
    @WebEndpoint(name = "OrderSoap12")
    public OrderSoap getOrderSoap12() {
        return super.getPort(OrderSoap12, OrderSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderSoap
     */
    @WebEndpoint(name = "OrderSoap12")
    public OrderSoap getOrderSoap12(WebServiceFeature... features) {
        return super.getPort(OrderSoap12, OrderSoap.class, features);
    }

}
