package com.transglobalexpress.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-25T20:45:06.690+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://services.transglobalexpress.co.uk/", name = "QuoteSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface QuoteSoap {

    @WebMethod(operationName = "QuoteConsignment", action = "http://services.transglobalexpress.co.uk/QuoteConsignment")
    @RequestWrapper(localName = "QuoteConsignment", targetNamespace = "http://services.transglobalexpress.co.uk/", className = "com.transglobalexpress.services.QuoteConsignment")
    @ResponseWrapper(localName = "QuoteConsignmentResponse", targetNamespace = "http://services.transglobalexpress.co.uk/", className = "com.transglobalexpress.services.QuoteConsignmentResponse")
    @WebResult(name = "QuoteConsignmentResult", targetNamespace = "http://services.transglobalexpress.co.uk/")
    public com.transglobalexpress.services.QuoteResponse quoteConsignment(
        @WebParam(name = "accountKey", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String accountKey,
        @WebParam(name = "heights", targetNamespace = "http://services.transglobalexpress.co.uk/")
        com.transglobalexpress.services.ArrayOfDecimal heights,
        @WebParam(name = "widths", targetNamespace = "http://services.transglobalexpress.co.uk/")
        com.transglobalexpress.services.ArrayOfDecimal widths,
        @WebParam(name = "lengths", targetNamespace = "http://services.transglobalexpress.co.uk/")
        com.transglobalexpress.services.ArrayOfDecimal lengths,
        @WebParam(name = "statedWeights", targetNamespace = "http://services.transglobalexpress.co.uk/")
        com.transglobalexpress.services.ArrayOfDecimal statedWeights,
        @WebParam(name = "dimensionUnits", targetNamespace = "http://services.transglobalexpress.co.uk/")
        com.transglobalexpress.services.ArrayOfString dimensionUnits,
        @WebParam(name = "weightUnits", targetNamespace = "http://services.transglobalexpress.co.uk/")
        com.transglobalexpress.services.ArrayOfString weightUnits,
        @WebParam(name = "fromCountryIso", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String fromCountryIso,
        @WebParam(name = "fromCity", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String fromCity,
        @WebParam(name = "fromPostcode", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String fromPostcode,
        @WebParam(name = "toCountryIso", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String toCountryIso,
        @WebParam(name = "toCity", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String toCity,
        @WebParam(name = "toPostcode", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String toPostcode,
        @WebParam(name = "itemType", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String itemType,
        @WebParam(name = "requiredCover", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.math.BigDecimal requiredCover
    );

    @WebMethod(operationName = "QuoteSinglePiece", action = "http://services.transglobalexpress.co.uk/QuoteSinglePiece")
    @RequestWrapper(localName = "QuoteSinglePiece", targetNamespace = "http://services.transglobalexpress.co.uk/", className = "com.transglobalexpress.services.QuoteSinglePiece")
    @ResponseWrapper(localName = "QuoteSinglePieceResponse", targetNamespace = "http://services.transglobalexpress.co.uk/", className = "com.transglobalexpress.services.QuoteSinglePieceResponse")
    @WebResult(name = "QuoteSinglePieceResult", targetNamespace = "http://services.transglobalexpress.co.uk/")
    public com.transglobalexpress.services.QuoteResponse quoteSinglePiece(
        @WebParam(name = "accountKey", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String accountKey,
        @WebParam(name = "height", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.math.BigDecimal height,
        @WebParam(name = "width", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.math.BigDecimal width,
        @WebParam(name = "length", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.math.BigDecimal length,
        @WebParam(name = "statedWeight", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.math.BigDecimal statedWeight,
        @WebParam(name = "dimensionUnit", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String dimensionUnit,
        @WebParam(name = "weightUnit", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String weightUnit,
        @WebParam(name = "fromCountryIso", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String fromCountryIso,
        @WebParam(name = "fromCity", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String fromCity,
        @WebParam(name = "fromPostcode", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String fromPostcode,
        @WebParam(name = "toCountryIso", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String toCountryIso,
        @WebParam(name = "toCity", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String toCity,
        @WebParam(name = "toPostcode", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String toPostcode,
        @WebParam(name = "itemType", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String itemType,
        @WebParam(name = "requiredCover", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.math.BigDecimal requiredCover
    );

    @WebMethod(operationName = "CalculateInsurance", action = "http://services.transglobalexpress.co.uk/CalculateInsurance")
    @RequestWrapper(localName = "CalculateInsurance", targetNamespace = "http://services.transglobalexpress.co.uk/", className = "com.transglobalexpress.services.CalculateInsurance")
    @ResponseWrapper(localName = "CalculateInsuranceResponse", targetNamespace = "http://services.transglobalexpress.co.uk/", className = "com.transglobalexpress.services.CalculateInsuranceResponse")
    @WebResult(name = "CalculateInsuranceResult", targetNamespace = "http://services.transglobalexpress.co.uk/")
    public com.transglobalexpress.services.QuoteInsuranceResponse calculateInsurance(
        @WebParam(name = "apiKey", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.lang.String apiKey,
        @WebParam(name = "requiredCover", targetNamespace = "http://services.transglobalexpress.co.uk/")
        java.math.BigDecimal requiredCover
    );
}
