package com.transglobalexpress.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-25T20:45:06.727+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "Quote", 
                  wsdlLocation = "http://staging.services.transglobalexpress.co.uk/Quote.asmx?WSDL",
                  targetNamespace = "http://services.transglobalexpress.co.uk/") 
public class Quote extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.transglobalexpress.co.uk/", "Quote");
    public final static QName QuoteSoap = new QName("http://services.transglobalexpress.co.uk/", "QuoteSoap");
    public final static QName QuoteSoap12 = new QName("http://services.transglobalexpress.co.uk/", "QuoteSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://staging.services.transglobalexpress.co.uk/Quote.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Quote.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://staging.services.transglobalexpress.co.uk/Quote.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public Quote(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Quote(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Quote() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Quote(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Quote(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Quote(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns QuoteSoap
     */
    @WebEndpoint(name = "QuoteSoap")
    public QuoteSoap getQuoteSoap() {
        return super.getPort(QuoteSoap, QuoteSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuoteSoap
     */
    @WebEndpoint(name = "QuoteSoap")
    public QuoteSoap getQuoteSoap(WebServiceFeature... features) {
        return super.getPort(QuoteSoap, QuoteSoap.class, features);
    }


    /**
     *
     * @return
     *     returns QuoteSoap
     */
    @WebEndpoint(name = "QuoteSoap12")
    public QuoteSoap getQuoteSoap12() {
        return super.getPort(QuoteSoap12, QuoteSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuoteSoap
     */
    @WebEndpoint(name = "QuoteSoap12")
    public QuoteSoap getQuoteSoap12(WebServiceFeature... features) {
        return super.getPort(QuoteSoap12, QuoteSoap.class, features);
    }

}
